---
- name: Install dependencies
  yum:
    name: rrdtool
    state: present
  tags:
    - rstudio-server

- name: Install R Studio Server
  yum:
    name: "{{ rstudio_server_package_name }}"
    state: "{{ rstudio_server_package_state }}"
    disable_gpg_check: yes
    update_cache: yes
  tags:
    - rstudio-server
