pp_serverport: 5432
pp_servicename: postgresql-10

rpm_url: https://packagecloud.io/install/repositories/citusdata/community/script.rpm.sh

citus_pkgs:
  - citus72_10

pp_shared_preload_libraries: citus
citus_memory_limit_service: MemoryMax

# Replication user
replication_user: replication
replication_password: replication
