---
- name: Verify install directory
  file: 
    path: "{{stata_install_directory}}/"
    state: directory

- name: Install expect
  yum: 
    name: expect
    state: present

- name: Unarachive the stata tarball
  unarchive:
    copy: yes
    src: "{{ stata_local_bin_directory }}/Stata14Linux64.tar.gz"
    dest: "{{ stata_install_directory }}/"

- name: Set permissions for the install script
  file:
    path: "{{ stata_install_directory }}/install"
    mode: 0755

- name: Copy the expect script
  template: 
    src: install_stata.exp
    dest: "{{stata_install_directory}}/install_stata.exp"
    mode: 0755

- name: Run stata install expect script
  shell: "./install_stata.exp"
  args:
    chdir: "{{stata_install_directory}}"

- name: Copy the stinit expect script
  template:
    src: stinit_stata.exp
    dest: "{{stata_install_directory}}/stinit_stata.exp"
    mode: a+rx

- name: Run the stata stinit expect script
  shell: "./stinit_stata.exp"
  args:
    chdir: "{{stata_install_directory}}"

# Do we need to source this?
- name: Copy configure_stata to /etc/profile.d
  template: 
    src: configure_stata.sh
    dest: /etc/profile.d/configure_stata.sh

- name: Remove the tarball
  file: 
    path: /tmp/Stata14Linux64.tar.gz
    state: absent
