---
- name: Verify install directory
  file:
    path: "{{ stata_install_directory }}/"
    state: directory
    owner: root
    group: root
  tags:
    - stata

- name: Ensure no installed files exist
  file:
    path: "{{ stata_install_directory }}/{{ item }}"
    state: absent
  with_items:
    - installed.150
    - stata
    - xstata
    - isstata.150
    - ado.tar
    - ado.tar.Z
    - base.tar
    - base.tar.Z
    - bins.tar
    - bins.tar.Z
    - docs.tar
    - docs.tar.Z
  tags:
    - stata

- name: Unarchive the stata tarball
  unarchive:
    copy: yes
    src: "{{ stata_local_bin_directory }}/{{ stata_tarball }}"
    dest: "{{ stata_install_directory }}/"
  when: custom_repo
  tags:
    - stata

- name: Set permissions for the install script
  file:
    path: "{{ stata_install_directory }}/install"
    mode: 0755
  when: custom_repo
  tags:
    - stata

- name: Install pip
  yum:
    name: python-pip
    state: present
  tags:
    - stata

- name: pip install pexpect
  pip:
    name: pexpect
    executable: /usr/bin/pip
  tags:
    - stata

- name: expect install
  expect:
    chdir: "{{ stata_install_directory }}"
    command: /bin/bash -c ./install
    timeout: 200
    responses:
        '.*Do you wish to continue.*': 'y'
        '.*Okay to proceed.*': 'y'
  register: expected
  failed_when: expected.rc != 0 and "no action taken" not in expected.stdout
  when: custom_repo
  tags:
    - stata

- name: Verify stata update directory
  file:
    path: "{{ stata_update_directory }}/"
    state: directory
    owner: root
    group: root
  when: stata_patch_update
  tags:
    - stata

- name: unarchive the stata update tarball
  unarchive:
    copy: yes
    src: "{{ stata_local_bin_directory }}/{{ stata_update_tarball }}"
    dest: "{{ stata_install_directory }}/"
  when: stata_patch_update
  tags:
    - stata

- name: Add the update do file
  template:
    src: stataupdate.do.j2
    dest: "{{ stata_install_directory }}/stataupdate.do"
  when: stata_patch_update
  tags:
    - stata

- name: Run the update do file (checks for updates, installs and restarts stata if updated)
  shell: "{{ stata_install_directory }}/stata-mp -b {{ stata_install_directory }}/stataupdate.do"
  when: stata_patch_update
  tags:
    - stata

- name: remove the stata update files
  file:
    path: "{{ stata_update_directory }}"
    state: absent
  when: stata_patch_update
  tags:
    - stata 

- name: Update permissions
  file:
    path: "{{ stata_install_directory }}"
    recurse: yes
    state: directory
    mode: "0755"
  tags:
    - stata

- name: expect stinit
  expect:
    chdir: "{{ stata_install_directory }}"
    command: /bin/bash -c ./stinit
    responses:
      '.*Do you agree to the License terms.*': 'Y'
      '.*Do you wish to continue.*': 'Y'
      '.*Serial number:.*': '{{ stata_serial_number }}'
      '.*Code:.*': '{{ stata_code }}'
      '.*Authorization:.*': '{{ stata_authorization }}'
      '.*Shall we continue.*': 'Y'
      '.*Enter what you would like the first line to say:.*': '{{ stata_line_one }}'
      '.*Enter what you would like the second line to say:.*': '{{ stata_line_two  }}'
      '.*Is this okay.*': 'Y'
  when: custom_repo
  tags:
    - stata

# Do we need to source this?
- name: Copy configure_stata to /etc/profile.d
  template:
    src: configure_stata.sh
    dest: /etc/profile.d/configure_stata.sh
  tags:
    - stata

- name: Create symlink to stata folder
  file:
    state: link
    src: "{{ stata_install_directory }}"
    dest: "{{ stata_directory }}"
  tags:
    - stata

- name: Create symlink to executable
  file:
    state: link
    src: "{{ stata_install_directory }}/xstata-mp"
    dest: "{{ stata_directory }}/stata"
  tags:
    - stata

- name: Copy sysprofile
  template:
    src: sysprofile.do.j2
    dest: "{{ stata_directory }}/sysprofile.do"
    mode: 0644
  tags:
    - stata

- name: Remove the tarball
  file:
    path: "/tmp/{{ stata_tarball }}"
    state: absent
  tags:
    - stata
