---
stattransfer_install_directory: /usr/local/StatTransfer12
stattransfer_local_bin_directory: /artifacts
stattransfer_license_type: "25 User Workgroup / Lease"
stattransfer_expiration_date: "August 31, 2015"
stattransfer_reg_code: STAT-TRANSFER-REG
stattransfer_auth_code: STAT-TRANSFER-AUTH
stattransfer_sign_code: STAT-TRANSFER-SIGN
