---
#- name: Install iptables-services
#  become: yes
#  become_method: sudo
#  command: yum install -y iptables-services
- name: Install iptables-services
  yum:
   name: iptables-services
   state: present
  when: iptables_config | bool
  tags:
    - iptables

- name: Make sure firewalld is masked
#  command: systemctl mask firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
    masked: yes
  tags:
    - iptables
    - never

- name: Enable iptables services
  systemd:
   name: "{{ item }}"
   state: started
   enabled: yes
  when: iptables_config | bool
#  command: systemctl enable "{{ item }}"
  with_items:
    - iptables
    - ip6tables

#- name: start iptables services
#  command: systemctl start "{{ item }}"
#  with_items:
#    - iptables
#    - ip6tables
