# main.yml - Kerberos client setup
---
- name: Install Kerberos
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - krb5-libs
    - krb5-workstation
    - krb5-devel
    - pam_krb5
    - sssd-krb5
    - sssd-krb5-common
    - libselinux-python

- name: Create log directory
  file:
    dest: /var/krb5
    state: directory

- name: Update krb5.conf configuration file
  template:
    src: krb5.conf
    dest: /etc/krb5.conf

- name: Create host principal
  command: kadmin -p {{ krb_service_user }}/admin -w {{ krb_service_user_password }} -q "addprinc -randkey host/{{ proxy_subdomain }}.{{ domain_name }}"
  when: create_keytabs
  run_once: True

- name: Add keytab for host
  command: kadmin -p {{ krb_service_user }}/admin -w {{ krb_service_user_password }} -q "ktadd host/{{ proxy_subdomain }}.{{ domain_name }}"
  when: create_keytabs
  run_once: True
