---
postgres_repository_url: "https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-6-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
postgres_repository_key_url: "https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-10"
postgres_repository_name: pgdg10
postgres_install_dir: /usr/pgsql-10
postgres_install_repository: True

postgres_packages:
  - postgresql10
  - postgresql10-devel

postgres_gis_packages:
  - postgis24_10

postgres_old_packages:
  - postgresql96
  - postgresql96-libs
  - postgis22
  - postgis24_96

clean_postgresql: False
