---
postgres_repository_url: "https://yum.postgresql.org/9.6/redhat/rhel-6-x86_64/pgdg-redhat96-9.6-3.noarch.rpm"
postgres_repository_key_url: "https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-96"
postgres_repository_name: pgdg96
postgres_install_dir: /usr/pgsql-9.6
postgres_install_repository: True

postgres_packages:
  - postgresql96
  - postgresql96-devel

postgres_old_packages:
  - postgresql
  - postgresql-libs
  - postgis22

clean_postgresql: False
