---
- name: Remove old java versions
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - java-1.6.0-openjdk
    - java-1.7.0-openjdk

- name: Install specified JDK version and dependencies
  yum:
    name: "{{ item }}"
    state: present
    disable_gpg_check: yes
  with_items: jdk_packages

- name: Ensure Java environment variables are set
  template:
    src: jdk.sh.j2
    dest: /etc/profile.d/jdk.sh

- name: Add additional deployment settings
  lineinfile:
    dest: "{{ jre_lib_path }}/deployment.properties"
    line: "{{ item }}"
    regexp: "{{ item }}"
    state: present
    create: yes
  with_items: java_deploy_options

- name: Add deployment config
  template:
    src: deployment.config
    dest: "{{ jre_lib_path }}/deployment.config"
