---
mesos_agent_log_file_locations:
  - /var/log/mesos

mesos_agent_package: mesos-0:1.4.1-2.0.1.x86_64
mesos_agent_version: 1.4.1
mesos_agent_port: 5051
mesos_agent_logging_level: "INFO"

mesos_agent_isolation: "cgroups/cpu,cgroups/mem,cgroups/net_cls,filesystem/linux,disk/du,docker/runtime"
mesos_agent_cgroups_path: "/cgroups"
mesos_agent_attributes: ""

mesos_agent_work_dir: "/opt/mesos"

mesos_agent_credential: "/etc/mesos_agent_credential"
mesos_agent_principal: "username"
mesos_agent_secret: "password"

mesos_agent_fix_link: True

# User to run processes in Mesos as
marathon_mesos_user: "mesagent"

# Container images
mesos_containerizers: "mesos"
mesos_launcher: "linux"
mesos_image_providers: "appc,docker"
mesos_agent_image_backend: "copy"

mesos_executor_registration_timeout: 5mins

mesos_appc_enable: yes
mesos_appc_simple_discovery_uri_prefix: "http://10.0.1.31:8080/v2/artifacts/appc/"
# File uri is not working, perhaps a bug in Mesos
#mesos_appc_simple_discovery_uri_prefix: file:///home/work/appc/
mesos_appc_store_dir: "/tmp/mesos/store/appc"

mesos_docker_enable: yes
mesos_docker_store_dir: "/tmp/mesos/store/docker"
mesos_docker_registry: "/home/work/mesos/docker/images"

mesos_cni_networks:
  - network_name: "default"
    nameservers:
      - "8.8.8.8"
      - "8.8.4.4"
