# deploy_admin_terminal.yml
---
- hosts: db_terminal
  become: yes
  become_method: sudo

  roles:
    - {role: puppet_disable, when: "disable_puppet"}
    - {role: iptables, when: "iptables_config"}
    - common
    - {role: epel, when: "use_epel and not 'production' in group_names"}
    - umask
    - {role: log-courier, when: "install_logstash"}
    - jdk
    - postgresql-client
    - eod
    - devtools
    - {role: python, when: "custom_repo"}
    - {role: python-build, when: "not custom_repo"}
    - python36-scl
    - python-libs
    - sqitch
    - {role: pem-client, tags: pem-client}
    - sublime
    - odbc
  tasks:

    - name: Install needed packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - htop
        - screen
        - rsync
        - unzip
        - gpg
        - pigz
        - facter
        - sysstat # sar, iostat, vmstat
        - systemtap # dtrace equivalent
        - ant

    - name: Install custom packages
      yum:
        name: "{{ item }}"
        state: "{{ db_automation_package_state }}"
        disable_gpg_check: yes
      with_items: "{{ db_automation_custom_packages }}"

  #      - https://github.com/Factual/drake
  #      - https://github.com/audreyr/cookiecutter
  #       sudo yum install perl-devel perl-CPAN && curl -L http://cpanmin.us | perl - --sudo App::cpanminus
  #       http://hammerora.sourceforge.net/download.html
  #       - ogr2ogr in GDAL
