# deploy_db_server.yml
---
- hosts: db_server
  sudo: yes
  roles:
    - {role: iptables, when: "iptables_config"}
    - {role: common, when: "install_glusterfs"}
    - {role: epel, when: "use_epel and not 'production' in group_names"}
    - {role: log-courier, when: "install_logstash"}
    - role: jdk
    - role: postgresql-server
    - role: postgresql-server-config
