---
- hosts: elasticsearch
  become: yes
  become_method: sudo
  roles:
    - common
    - {role: puppet_disable, when: "disable_puppet"}
    - {role: iptables, when: "iptables_config"}
    - {role: epel, when: "use_epel and not 'production' in group_names"}
    - elasticsearch
    - {role: log-courier, when: "install_logstash"}
    - elasticsearch-config
