# deploy_mesos_master.yml
---
- hosts: mesos_master
  become: yes
  become_method: sudo
  serial: 1
  max_fail_percentage: 30
  roles:
    - {role: iptables, when: "iptables_config"}
    - common
    - mesos_master

