---
- hosts: elk
  become: yes
  become_method: sudo
  roles:
    - common
    - {role: puppet_disable, when: "disable_puppet"}
    - {role: iptables, when: "iptables_config"}
    - {role: epel, when: "use_epel and not 'production' in group_names"}
    - jdk
    - elasticsearch

- hosts: elk
  become: yes
  become_method: sudo
  handlers:
    - import_tasks: roles/shared/handlers/main.yml
  pre_tasks:
    - name: Create key for message authentication
      shell: "/usr/share/elasticsearch/bin/shield/syskeygen"
      args:
        creates: /etc/elasticsearch/shield/system_key
      register: create_key
      when: es_message_auth_enabled
      environment:
        ES_JAVA_OPTS: "-Des.path.conf=/etc/elasticsearch"

    - name: Ensure permissions are correct
      file:
        dest: /etc/elasticsearch/shield/system_key
        owner: "{{ es_user }}"
        group: "{{ es_user }}"
        mode: 0600
      when: es_message_auth_enabled

    - name: Fetch the key
      fetch:
        src: /etc/elasticsearch/shield/system_key
        dest: ./
        fail_on_missing: yes
        flat: yes
      when: es_message_auth_enabled and create_key.changed

  roles:
    - elasticsearch-config
    - logstash
    - logstash-config
    - kibana
    - kibana-config
    - {role: log-courier, when: "install_logstash"}
