# rhel_7.yml - Sets up iptables for rhel7

---
- name: Install iptables-services
# become: yes
# become_method: sudo
  command: yum install -y iptables-services
# yum:
#   name: iptables-services
#   state: present

- name: Make sure firewalld is masked
  command: systemctl mask firewalld
# systemd:
#   name: firewalld
#   masked: yes

- name: Enable iptables services
# systemd:
#   name: "{{ item }}"
#   state: started
#   enabled: yes
  command: systemctl enable "{{ item }}"
  with_items:
    - iptables
    - ip6tables
- name: start iptables services
  command: systemctl start "{{ item }}"
  with_items:
    - iptables
    - ip6tables
