---
- name: Install elasticsearch GPG key
  rpm_key:
    key: https://packages.elasticsearch.org/GPG-KEY-elasticsearch
    validate_certs: no   # TODO remove on rhel7
    state: present
  when: kibana_use_repository

- name: Install the Kibana repository
  template:
    src: kibana.repo.j2
    dest: /etc/yum.repos.d/kibana.repo
  when: not "production" in group_names and kibana_use_repository

- name: Install Kibana
  yum:
    name: kibana
    state: present
  when: kibana_use_repository

### OLD WAY
- name: Get the Kibana tar
  get_url:
    url: https://download.elasticsearch.org/kibana/kibana/kibana-4.0.2-linux-x64.tar.gz
    dest: /tmp
  when: not kibana_use_repository

- name: Extract the Kibana tar
  unarchive:
    copy: no
    src: /tmp/kibana-4.0.2-linux-x64.tar.gz
    dest: /opt/
    creates: /opt/kibana/bin/kibana
  when: not kibana_use_repository

- name: Rename the kibana directory for convenience
  command: mv /opt/kibana-4.0.2-linux-x64 /opt/kibana
  args:
    creates: /opt/kibana
    removes: /opt/kibana-4.0.2-linux-x64
  when: not kibana_use_repository

- name: Install Kibana upstart script
  template:
    src: kibana.conf
    dest: /etc/init/kibana.conf
  notify:
    - restart kibana
  when: not kibana_use_repository

- name: Open ports 5601 in iptables
  command: "iptables -I {{ iptables_chain }} 3 -m state --state NEW -p tcp --dport 5601 -s {{ hostvars[groups['proxy_server'][0]]['ansible_ssh_host'] }} -j ACCEPT"
  when: iptables_config and deploy_iptables

- name: Save rules
  command: "/sbin/service iptables save"
  when: iptables_config and deploy_iptables

- name: Enable Kibana
  service:
    name: kibana
    enabled: yes
