
# file: aurora/deploy/roles/nginx/defaults/main.yml
---

deploy_user: vagrant

nginx_listen: 80

nginx_user: nginx
nginx_group: nginx

nginx_dir: "/etc/nginx"
nginx_log_dir: "/var/log/nginx"
nginx_error_log: "/var/log/nginx/error.log"
nginx_error_log_format: warn
nginx_access_log: "/var/log/nginx/access.log"
nginx_access_log_format: main
nginx_pid: "/var/run/nginx.pid"
nginx_conf_dir: "/etc/nginx/conf.d"
nginx_certificate_files: {}

# nginx.conf
nginx_sendfile: "on"
nginx_tcp_nopush: "on"
nginx_tcp_nodelay: "on"
nginx_keepalive_timeout: "0"
nginx_worker_processes: 1
nginx_worker_connections: 1024
nginx_client_max_body_size: "1k"
nginx_client_header_buffer_size: "1k"
nginx_client_body_buffer_size: "1k"
nginx_large_client_buffers: "2 1k"

# disabling version number display
nginx_server_tokens: 'off'

# Blocking download agents and configuring nginx to return error message
nginx_block_download_agents: "$http_user_agent ~* msnbot|scrapbot"
nginx_block_robots: "$http_user_agent ~* LWP::Simple|BBBike|wget"
nginx_webcrawler_protect: "(.*).test.dev"

# Nginx initial state
nginx_state: "started"
nginx_enable: "yes"

# Access restrictions
nginx_access_list:
  -
    type: allow
    address: all
