---
- name: Install dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - perl-devel
    - perl-CPAN
    #- perl-DBD-Pg
    - "@Development Tools"

- name: Ensure umask is correct
  sudo: no
  lineinfile:
    dest: ~/.bashrc
    line: umask 0022
    regexp: ^(.*)umask(.*)$
    state: present

- name: Get CPAN Minus itself
  get_url:
    url: http://cpanmin.us
    dest: /tmp/cpanminus.pl

- name: Run with perl
  shell: perl /tmp/cpanminus.pl --sudo App::cpanminus
  args:
    creates: /usr/local/bin/cpanm

- name: Get sqitch
  shell: cpanm --notest --sudo App::Sqitch
  args:
    creates: /usr/local/bin/sqitch
  environment:
    PATH: /usr/pgsql-9.4/bin/:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

- name: Get pg engine
  shell: cpanm --notest --sudo DBD::Pg
  environment:
    PATH: /usr/pgsql-9.4/bin/:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
