---
- name: Install dependencies
  yum:
    name: ['perl-devel', 'perl-CPAN', '@Development Tools'] # perl-DBD-Pg
    state: present
  tags:
    - sqitch

- name: Ensure umask is correct
  become: no
  lineinfile:
    dest: ~/.bashrc
    line: umask 0022
    regexp: ^(.*)umask(.*)$
    state: present
  tags:
    - sqitch

- name: Get CPAN Minus itself
  get_url:
    url: http://cpanmin.us
    dest: /tmp/cpanminus.pl
  tags:
    - sqitch

- name: Run with perl
  shell: perl /tmp/cpanminus.pl --sudo App::cpanminus
  args:
    creates: /usr/local/bin/cpanm
  tags:
    - sqitch

- name: Get Datetime
  shell: cpanm --notest --sudo DateTime::TimeZone
  register: timezone
  changed_when: '"is up to date" not in timezone.stdout'
  environment:
    PATH: "{{ postgres_install_dir }}/bin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
  tags:
    - sqitch
  when: install_sqitch

- name: Get sqitch
  shell: cpanm --notest --sudo App::Sqitch
  register: sqitch
  changed_when: '"is up to date" not in sqitch.stdout'
  environment:
    PATH: "/usr/pgsql/bin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
  tags:
    - sqitch
  when: install_sqitch

- name: Get pg engine
  shell: cpanm --notest --sudo DBD::Pg
  register: pg_engine
  changed_when: '"is up to date" not in pg_engine.stdout'
  environment:
    PATH: "/usr/pgsql/bin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
  when: postgres_install_dir is defined
  tags:
    - sqitch

- name: Add usr/local/bin directory to path
# when login to db terminal through EoD, /usr/local/bin directory is not in the PATH, sqitch is not found
  template:
    src: sqitch.sh.j2
    dest: /etc/profile.d/sqitch.sh
    mode: 0644
  tags:
    - sqitch
