# main.yml - Installs Python 2.7 from custom RPM
---
- name: Make sure rpmbuild is empty
  sudo: no
  file:
    path: "~/rpmbuild"
    state: absent

- name: Make sure git is installed
  sudo: yes
  yum:
    name: git
    state: latest

- name: Clone git repo
  sudo: no
  git:
    dest: "~/python34"
    repo: https://github.com/cfpb/python34-for-el6.git

- name: Run bootstrap script
  sudo: no
  command: "sh ./bootstrap.sh"
  args:
    chdir: "~/python34"

- name: Build python RPM
  sudo: no
  command: "rpmbuild -ba SPECS/python34-alt.spec"
  args:
    chdir: "~/rpmbuild"
    creates: "~/rpmbuild/RPMS/x86_64/python34-3.4.3-1.el6.x86_64.rpm"

- name: Copy RPM to /tmp so it is accessible by root
  sudo: no
  command: "cp ~/rpmbuild/RPMS/x86_64/python34-3.4.3-1.el6.x86_64.rpm /tmp/python34-3.4.3-1.el6.x86_64.rpm"
  args:
    creates: "/tmp/python34-3.4.3-1.el6.x86_64.rpm"

- name: Install python
  sudo: yes
  yum:
    name: "/tmp/python34-3.4.3-1.el6.x86_64.rpm"
    state: present
