---
# For now, we will install from a tarball, but we may move
# to using a custom RPM, hence the commented out lines.

# - name: Install intellij rpm
#   yum:
#     name: "intellij"
#     state: present
#   when: custom_repo
#   tags:
#   - intellij

- name: Download intellij
  get_url:
    url: "{{ intellij_url }}"
    dest: "/tmp/intellij-{{ intellij_version }}"
  # when: not custom_repo
  tags:
  - intellij

- name: Create install directory
  file:
    path: "{{ intellij_install_dir }}"
    state: directory
    mode: 0755
  tags:
  - intellij

- name: Extract intellij from /tmp
  unarchive:
    src: "/tmp/intellij-{{ intellij_version }}"
    dest: "{{ intellij_install_dir }}"
    copy: no
  # when: not custom_repo
  tags:
  - intellij

- name: Create symlink for idea.sh
  file:
    src: "{{ intellij_install_dir }}/{{ intellij_idea_dir }}/bin/idea.sh"
    dest: "{{ intellij_main_dir }}/bin/idea.sh"
    state: link
  # when: not custom_repo
  tags:
  - intellij

- name: Install Intellij IDEA desktop file
  template:
    src: idea.desktop.j2
    dest: "{{ intellij_desktop_dir }}/idea.desktop"
    mode: 0644
  # when: not custom_repo
  tags:
  - intellij

- name: Set up idea.png
  template:
    src: idea.png.j2
    dest: "{{ intellij_main_dir }}/bin"
  # when: not custom_repo
  tags:
  - intellij
