---
- name: Get JDBC driver JAR file for postgresql
  get_url:
    url: "{{ jdbc_postgres_url }}"
    dest: "{{ jre_lib_path }}/"
    mode: 0644

- name: Get the JDBC driver for SQLServer
  unarchive:
    src: "{{ jdbc_sql_url }}"
    dest: "/tmp"
    copy: no

- name: Move the JAR file to the right location
  copy:
    src: "/tmp/sqljdbc42.jar"
    dest: "{{ jre_lib_path }}"
    remote: no
    mode: 0644
