# main.yml - Role for configuring kerberos to work with apache
---
- name: Create http principal
  command: kadmin -p {{ krb_service_user }}/admin -w {{ krb_service_user_password }} -q "addprinc -randkey HTTP/{{ proxy_subdomain }}.{{ domain_name }}"
  when: create_keytabs and kerberos_enabled
  run_once: True

- name: Add keytab for http
  command: kadmin -p {{ krb_service_user }}/admin -w {{ krb_service_user_password }} -q "ktadd -k /etc/httpd/http.keytab HTTP/{{ proxy_subdomain }}.{{ domain_name }}"
  args:
    creates: /etc/httpd/http.keytab
  when: create_keytabs and kerberos_enabled
  register: created_http_keytab

- name: Update permissions
  file:
    path: /etc/httpd/http.keytab
    state: touch
    owner: apache
    group: apache
  when: create_keytabs and created_http_keytab

- name: Install mod_auth_kerb and mod_authz_ldap (6.x)
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - mod_auth_kerb
    - mod_authz_ldap
  when: ansible_distribution_major_version == "6"

- name: Install mod_auth_kerb and mod_ldap (7.x)
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - mod_auth_kerb
    - mod_ldap
  when: ansible_distribution_major_version == "7"

- name: Update neccessary LDAP setting
  lineinfile:
    dest: /etc/openldap/ldap.conf
    line: "REFERRALS off"
    state: present
    insertafter: EOF
