---
- name: Create app directory
  file:
    dest: /opt/shiny-server/apps
    state: directory
    mode: 0755
  tags:
    - shiny
    - config

- name: Load config file
  template:
    src: shiny-server.conf.j2
    dest: /etc/shiny-server/shiny-server.conf
  tags:
    - shiny
    - config
  notify:
    - restart shiny-server

- name: Ensure Shiny Server is started
  service:
    name: shiny-server
    state: started
  tags:
    - shiny
