---
- name: Ensure opt folder exists
  file:
    dest: /opt
    state: directory

- name: Ensure unzip is installed
  yum:
    name: unzip
    state: present

- name: Extract Pentaho
  unarchive:
    src: "{{ pentaho_zip_path }}/{{ pentaho_zip_file }}"
    dest: /opt/
    creates: /opt/data-integration/lib/kettle-core-{{ pentaho_version }}.jar

- name: Create desktop shortcut for Pentaho
  template:
    src: pentaho.desktop.j2
    dest: /usr/share/applications/pentaho.desktop
    mode: 0644

- name: Get the JDBC driver for SQLServer
  unarchive:
    src: "{{ jdbc_sql_url }}"
    dest: "/tmp/sqljdbc"

- name: Move the JAR file to the right location
  copy:
    src: "/tmp/sqljdbc/sqljdbc42.jar"
    dest: "/opt/data-integration/lib/"
    remote: no
    mode: 0644

- name: Add an option to disable cairo, which is buggy in this case
  lineinfile:
    line: OPT="$OPT -Dorg.eclipse.swt.internal.gtk.cairoGraphics=false"
    insertafter: $OPT\=\"$OPT $PENTAHO_DI_JAVA_OPTIONS\".*
    state: present

- name: Set memory usage
  lineinfile:
    regexp: $(.*)PENTAHO_DI_JAVA_OPTIONS=\"(.*)\"
    line: "    PENTAHO_DI_JAVA_OPTIONS=\"-Xmx{{ pentaho_heap_size }} -XX:MaxPermSize={{ pentaho_perm_size }}\""
    state: present
