# main.yml - Apache installation and setup
---
- name: Add Apache repo
  yum:
    name: centos-release-scl
    state: present
  when: not custom_repo
  tags:
    - apache

- name: Install Apache
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ apache_packages }}"
  tags:
    - apache

- name: Configure global Apache settings
  template:
    src: httpd.conf.j2
    dest: "{{ apache_config_path }}"
    mode: 644
    owner: apache
    group: apache
  tags:
    - apache

- name: Ensure other processes are not running
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items: "{{ apache_disabled_services }}"
  tags:
    - apache

# We ignore errors here, since the actual host configuration
# will happen elsewhere in the playbook, so error states should
# be corrected later, at which point Apache will trigger an
# error if things still aren't correct.
- name: Ensure Apache is started and enabled on boot.
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes
  failed_when: False
  tags:
    - apache

- name: Open port 80 in iptables
  command: "iptables -I {{ iptables_chain }} 3 -m state --state NEW -p tcp --dport 80 -j ACCEPT"
  when: iptables_config
  tags:
    - apache

- name: Open port 443 in iptables
  command: "iptables -I {{ iptables_chain }} 3 -m state --state NEW -p tcp --dport 443 -j ACCEPT"
  when: iptables_config
  tags:
    - apache

- name: Save rules
  command: "/sbin/service iptables save"
  when: iptables_config
  tags:
    - apache

- name: create certs for apache localhost
  command: openssl req -x509 -nodes -days 365 -newkey rsa:2048 -subj "/C=US/ST=CFPB/L=Washington/O=Dis/CN=www.cf.gov" -keyout /etc/pki/tls/private/localhost.key -out /etc/pki/tls/certs/localhost.crt
  args:
    creates: /etc/pki/tls/certs/localhost.crt
  when: not custom_repo
  tags:
    - apache

- name: Set recursive admin permissions on log folders
  acl:
    path: "{{ apache_log_folder }}"
    entity: "{{ restricted_group_name }}"
    etype: group
    permissions: rX
    recursive: yes
    state: present
  tags:
    - apache

- name: Set default admin permissions on log folders
  acl:
    path: "{{ apache_log_folder }}"
    entity: "{{ restricted_group_name }}"
    etype: group
    permissions: rX
    default: yes
    state: present
  tags:
    - apache
