# main.yml - Apache installation and setup
---
- name: Add Apache 2.4 Repository
  get_url:
    url: "{{ apache_24_repo }}"
    dest: /etc/yum.repos.d
    mode: 644
  when: apache_24_repo is defined and not 'production' in group_names

- name: Install Apache
  yum:
    name: "{{ item }}"
    state: present
  with_items: apache_packages

- name: Configure global Apache settings
  template:
    src: httpd.conf.j2
    dest: "{{ apache_config_path }}"
    mode: 644
    owner: apache
    group: apache

- name: Ensure other processes are not running
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items: "{{ apache_disabled_services }}"

# We ignore errors here, since the actual host configuration
# will happen elsewhere in the playbook, so error states should
# be corrected later, at which point Apache will trigger an
# error if things still aren't correct.
- name: Ensure Apache is started and enabled on boot.
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes
  failed_when: False

- name: Open port 80 in iptables
  command: "iptables -I {{ iptables_chain }} 3 -m state --state NEW -p tcp --dport 80 -j ACCEPT"
  when: iptables_config

- name: Open port 443 in iptables
  command: "iptables -I {{ iptables_chain }} 3 -m state --state NEW -p tcp --dport 443 -j ACCEPT"
  when: iptables_config

- name: Save rules
  command: "/sbin/service iptables save"
  when: iptables_config
