---
- name: Setup logstash-courier input
  template:
    src: 01-logstash-courier-input.conf
    dest: /etc/logstash/conf.d/01-logstash-courier-input.conf
  when: install_logstash
  notify:
    - restart logstash

- name: Setup syslog filter
  template:
    src: 10-syslog.conf
    dest: /etc/logstash/conf.d/10-syslog.conf
  notify:
    - restart logstash

- name: Setup elasticsearch output
  template:
    src: 30-lumberjack-output.conf
    dest: /etc/logstash/conf.d/30-lumberjack-output.conf
  notify:
    - restart logstash

- name: Add custom filters
  copy:
    src: "{{ item }}"
    dest: "/etc/logstash/conf.d/{{ item }}"
    mode: 0644
  with_items: "{{ logstash_filters }}"

- name: Ensure permissions are correct
  shell: "chmod 644 /etc/logstash/conf.d/*"
  notify:
    - restart logstash

- name: Ensure logstash is started
  service:
    name: logstash
    state: started
    enabled: yes
